import 'package:flutter/material.dart';
import 'package:json/Provider/example_two_provider.dart';
import 'package:provider/provider.dart';

class ExampleTwo extends StatefulWidget {
  const ExampleTwo({Key? key}) : super(key: key);

  @override
  State<ExampleTwo> createState() => _ExampleTwoState();
}

class _ExampleTwoState extends State<ExampleTwo> {
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    final postProvider = Provider.of<ExampleTwoProvider>(context,listen: false);
    postProvider.getExampleTwo();
  }
  Widget build(BuildContext context) {
    final provider = Provider.of<ExampleTwoProvider>(context);
    return Scaffold(
      body: ListView.builder(
        itemCount: provider.autogenerated.length,
          itemBuilder: (context,index){
          var data = provider.autogenerated[index];
          return Card(
            child: Column(
              children: [
                Text('${data.id}'),
                Text('${data.userId}'),
                Text('${data.title}'),
                Text('${data.body}'),
              ],
            ),
          );
          }
      ),
    );
  }
}
