import 'dart:convert';

import 'package:flutter/material.dart';
import '../Model/model.dart';
import 'package:http/http.dart' as http;

class HomePage extends StatefulWidget {
  const HomePage({Key? key}) : super(key: key);

  @override
  State<HomePage> createState() => _HomePageState();
}
List<Autogenerated> autogenerated = [];

class _HomePageState extends State<HomePage> {
  Future<List<Autogenerated>> getAutogenerated()async{
    var response = await http.get(Uri.parse('https://jsonplaceholder.typicode.com/posts'));
    print(response.body);
    if(response.statusCode == 200){
      var jsonParse = jsonDecode(response.body.toString());
      for(var data in jsonParse){
        Autogenerated model = Autogenerated.fromJson(data);
        autogenerated.add(model);
      }
    }
    return autogenerated;
  }

  @override
  void initState() {
    // TODO: implement initState
    super.initState();
    getAutogenerated();
  }
  Widget build(BuildContext context) {
    return Scaffold(
      body: FutureBuilder(
        future: getAutogenerated(),
        builder: (context,snapshot){
          if(snapshot.hasData){
            return ListView.builder(
              itemCount: snapshot.data?.length,
                itemBuilder: (context,index){
                return Padding(
                  padding: const EdgeInsets.symmetric(horizontal: 10.0),
                  child: Card(
                    child: Column(
                      children: [
                        Text('id: ${snapshot.data![index].id}'),
                        Text('user: ${snapshot.data![index].userId}'),
                        Text('title: ${snapshot.data![index].title}'),
                        Text('body: ${snapshot.data![index].body}'),
                        SizedBox(
                          height: 20.0,
                        ),

                      ],
                    ),
                  ),
                );
                });
          }else{
            return Text('data not Add');
          }
        },
      ),
    );
  }
}
